version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    # Stop the running container before installing new files
    - location: scripts/stop_container.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    # Start the new container using docker compose
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user