version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  # CRITICAL FIX: The installation must happen FIRST.
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
      sudo: true
      
  # The stop script runs AFTER installation, ensuring 'docker compose' exists.
  AfterInstall:
    - location: scripts/stop_container.sh
      timeout: 60
      runas: ec2-user
      sudo: true

  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user
      sudo: true