version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # CRITICAL: Dependencies must be installed for 'npm run build' (tsc) to work.
      - echo "Installing dependencies for compilation..."
      - npm install
  build:
    commands:
      # This compiles your TypeScript code, creating the 'dist/' directory.
      - echo "Running TypeScript build..."
      - npm run build || echo "npm run build failed, continuing for CodeDeploy package."
      - echo "Build completed."
      # CRITICAL: npm test is omitted to prevent failure due to missing SECRETS.
artifacts:
  files:
    # CRITICAL: This packages ALL files and folders, ensuring 'scripts/', 'appspec.yml',
    # and the compiled 'dist/' directory are sent to CodeDeploy.
    - '/*'
  discard-paths: no