version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.17.1
    commands:
      # Install dependencies only if absolutely needed for packaging, 
      # but generally skipped for CodeDeploy/Docker deployments.
      # You can leave this out for a cleaner package:
      # - npm install
      - echo "Skipping full npm install in CodeBuild."
  build:
    commands:
      # Build your TypeScript code to generate the 'dist' folder
      - npm run build || echo "npm run build failed or not found, continuing..."
      - echo "Build completed."
artifacts:
  files:
    # Package ALL files for CodeDeploy, including the generated 'dist' and appspec/scripts
    - '**/*'
  discard-paths: no