# =============================================================================
# Docker Compose - Nexus Auth Service (Production Deployment)
# Defines only the 'auth-service'. External dependencies are fetched securely 
# via the start_container.sh script at runtime.
# =============================================================================

version: '3.8'

services:
  # -----------------------------------------------------------------------------
  # Nexus Auth Service
  # -----------------------------------------------------------------------------
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-auth-prod
    ports:
      - "4001:4001" # Host:Container mapping
    environment:
      # These are placeholders; they will be overridden by the secure script (start_container.sh)
      - NODE_ENV=production
      - PORT=4001
      # Note: We rely on the start_container.sh script to inject all SECRETS at runtime.
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - nexus-network

# =============================================================================
# Networks
# =============================================================================
networks:
  nexus-network:
    driver: bridge
    name: nexus-network
# We removed all volumes (postgres_data, redis_data) as local databases are not used.